export const SUPPORT_CHATS_LOADING = "SUPPORT_CHATS_LOADING";
export const SUPPORT_CHATS_SET_USERS = "SUPPORT_CHATS_SET_USERS";
export const SUPPORT_CHATS_ERROR   = "SUPPORT_CHATS_ERROR";
export const SUPPORT_CHATS_SET_CHATS = "SUPPORT_CHATS_SET_CHATS";
export const SUPPORT_CHATS_PUSH_CHAT = "SUPPORT_CHATS_PUSH_CHAT";
